package Boxer::Graphic::Object::Base::Add;

use Moose;

with 'Boxer::Graphic';

sub BUILD {
    my ( $self ) = @_;
    $self->never_expanded( 1 );
}

sub icon {
    return [
        {
            b => [ 0.3, 0.9, 0.4 ],
        },
        qq{
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        bbbbbbbbbbbbbbbb
        bbbbbbbbbbbbbbbb
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
        .......bb.......
    } ];
}

1;
